name = "flashtap-staging"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "staging"
NEXT_PUBLIC_SUPABASE_URL = "https://mdqjpxwczrhkxkbqatqa.supabase.co"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "c12172a326a94cc39e874eb2e7cd9a69"
