import type { StationKind } from '@/lib/stations/station-pairing'
import { STATION_PWA } from '@/lib/stations/pwa'

/**
 * ONE-CLICK PAIRING — AND DELIBERATELY NOT A NEW CREDENTIAL.
 *
 * ============================================================================================
 * WHY THIS CARRIES THE EXISTING ACTIVATION CODE
 * ============================================================================================
 *
 * A pairing link grants pairing, so it IS an auth path. The requirements for one are: server
 * issued, bound to a venue and a station, short lived, single use, invalidated on use, not
 * guessable, not replayable.
 *
 * The activation code already satisfies every one of those:
 *
 *   - generated by `generateTerminalActivationCode` from `crypto.getRandomValues`, which THROWS
 *     rather than falling back to Math.random;
 *   - written onto a `restaurant_terminals` row that carries restaurant_id and station_kind, so
 *     the binding is the row itself, not something the URL asserts;
 *   - one hour expiry (`activation_code_expires_at`);
 *   - cleared on redemption by POST /api/terminals/activate, so a second use finds nothing;
 *   - that route is rate limited (lib/terminals/activation-rate-limit.ts);
 *   - never returned by the list endpoint.
 *
 * Minting a SECOND kind of pairing secret would mean a second expiry to get right, a second
 * revocation path to remember, and a second thing to audit — to obtain exactly the properties the
 * first one already has. So this is a delivery mechanism for the existing code and nothing more.
 * Nothing about how a code is issued or redeemed changes.
 *
 * ============================================================================================
 * WHAT PUTTING IT IN A URL COSTS, AND WHAT PAYS FOR IT
 * ============================================================================================
 *
 * A code in a URL lands in browser history. Against that: it is single use, so history holds a
 * spent code; it expires within the hour regardless; the page strips it from the address bar the
 * moment it is read (`stripActivationParam`), so it does not survive a reload or get carried into
 * a bookmark; and the station board never navigates outward, so there is no referrer to leak it to.
 *
 * The alternative in practice is a human reading eight characters off a laptop and typing them
 * into a wall screen — which is the step that produced a screen paired to the wrong venue, because
 * the code came from a page nobody checked the venue of. The typed path REMAINS as the fallback.
 *
 * NO QR. The KDS is a Windows PC with no camera. A QR would need a phone to relay a code between
 * two machines that are already both in front of the operator — an extra hop and an extra device
 * for no security gain.
 */
export const ACTIVATION_LINK_PARAM = 'activate'

/** The link an operator opens ON the screen being paired. */
export function stationActivationLink(station: StationKind, activationCode: string, origin = ''): string {
  const params = new URLSearchParams({ [ACTIVATION_LINK_PARAM]: activationCode })
  return `${origin}${STATION_PWA[station].startUrl}?${params.toString()}`
}

/** Read a code out of a launch URL. Empty/absent is the overwhelmingly common case. */
export function readActivationCode(search: string): string | null {
  try {
    const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search)
    const code = (params.get(ACTIVATION_LINK_PARAM) ?? '').trim()
    return code || null
  } catch {
    return null
  }
}

/**
 * Remove the code from the address bar without navigating.
 *
 * Called the instant the code has been READ, before it is even submitted — so a failed activation
 * cannot leave a spent-or-invalid code sitting in the URL to be reloaded, bookmarked or screenshotted.
 * Any other parameters (the venue hint) are preserved.
 */
export function stripActivationParam(search: string): string {
  try {
    const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search)
    params.delete(ACTIVATION_LINK_PARAM)
    const rest = params.toString()
    return rest ? `?${rest}` : ''
  } catch {
    return ''
  }
}
