-- @env: production
--
-- #127 — THE PRODUCTION HALF OF THE UNIQUE ORDER-NUMBER INDEX.
--
-- ============================================================================================
-- WHY A SECOND FILE INSTEAD OF EDITING 20260809120000
-- ============================================================================================
--
-- `20260809120000_orders_unique_order_number.sql` creates this exact index and is scoped
-- `-- @env: staging`. It is APPLIED on staging and recorded in staging's ledger. #127's recorded
-- plan is to drop that scope once production is clean, and that remains a fine way to do it.
--
-- This file exists so the production side can be prepared, reviewed and staged as a normal
-- migration WITHOUT touching a file that is already applied somewhere. The two are idempotent
-- against each other: same index NAME, same columns, same predicate, `IF NOT EXISTS`. Whichever
-- runs first creates it; the other is a no-op that still records a ledger row. If the scope on
-- 20260809120000 is dropped later, nothing here breaks and nothing needs undoing.
--
-- SCOPED `production` AND NOT `both` for one measured reason: staging ALREADY HAS this index
-- under this name, applied 2026-08-09 and recorded against version 20260809120000. An unscoped
-- file would read as LOCAL_NOT_APPLIED on staging and block staging deploys over an object that
-- is demonstrably present.
--
-- ============================================================================================
-- THIS CANNOT BE APPLIED TO PRODUCTION TODAY. TWO THINGS MUST HAPPEN FIRST.
-- ============================================================================================
--
-- Measured on production 2026-08-26 by scripts/prod/probe-127-duplicate-order-numbers.mjs:
--
--   duplicate (firebase_restaurant_id, order_number) groups   283
--     all rows are #324 stress fixtures                       279 groups,  941 blocking rows
--     all rows are real orders                                  4 groups,    4 blocking rows
--     MIXED                                                     0 groups,    0 rows
--
-- `CREATE UNIQUE INDEX` aborts on the first duplicate, so both populations have to go:
--
--   1. #324's delete — `scripts/prod/delete-324-orphan-orders.ts`. Removes 941 of the 945
--      blocking rows. Safe because ZERO groups are mixed: no group holds a fixture AND a real
--      order, so the delete cannot strand a real order or half-resolve a collision. That zero was
--      re-derived from production, not carried over from the issue.
--
--   2. The four real duplicates renumbered — `scripts/prod/renumber-127-duplicate-orders.ts`.
--      All four are FNB ChowNow POS orders, all sub-second, and they are live paid records, so
--      this is a decision about customer data rather than a cleanup.
--
-- THE ORDER MATTERS AND IT IS NOT THE ORDER RECORDED ON #127. The allocator change in
-- `lib/orders/order-number.ts` must be DEPLOYED BEFORE THIS INDEX, not after it. With the index
-- in place, the old `count(*) + 1` allocator raises 23505 on every attempt for a venue the moment
-- any order row is deleted — the same number, forever, because count(*) is deterministic. That is
-- a venue that cannot take orders until someone edits the database. `max(order_number) + 1`
-- cannot enter that state.
--
-- ============================================================================================
-- WHY THIS SCOPE, WITH THE ALTERNATIVE STATED
-- ============================================================================================
--
-- `firebase_restaurant_id`, matching 20260809120000 and the allocator. The constraint and the
-- allocator must agree on scope or the constraint rejects valid inserts while still permitting
-- the collision it exists to stop.
--
-- The alternative is `(restaurant_id, order_number)`, and it is worth recording because it is
-- NOT equivalent in the one way that matters here. On production, measured:
--
--   firebase ids spanning more than one restaurant_id        0
--   restaurant_ids carrying more than one firebase id        0
--   real rows with a restaurant_id and no firebase id        0
--   real rows with a firebase id and no restaurant_id        0
--
-- So for real data the two keys are interchangeable. The difference is entirely #324's fixtures:
-- they carry a firebase id and a NULL restaurant_id, and Postgres treats NULLs as distinct in a
-- unique index. On the restaurant_id key those 941 blocking rows DO NOT BLOCK AT ALL, and step 1
-- above stops being a prerequisite — the index would be blocked only by the four real duplicates.
--
-- That is a live option for whoever owns this index, and it is recorded rather than taken,
-- because the scope choice on 20260809120000 is a decision already made.
--
-- ============================================================================================
-- SHAPE
-- ============================================================================================
--
-- PARTIAL, on both columns being NOT NULL. Production carries one order row with a NULL
-- order_number and one with a NULL firebase_restaurant_id (the same row: status 'test', from
-- 2026-06-16 — the row that also blocks the orders.status CHECK constraint, and which #324's
-- delete does NOT reach because its predicate requires `restaurant_test_%`). NULLs are already
-- distinct in a unique index, so the predicate does not change which rows conflict; it states the
-- intent and keeps the index off the rows the pair is meaningless for.
--
-- NOT CONCURRENTLY: the real table is ~2200 rows, the lock is momentary, and CREATE INDEX
-- CONCURRENTLY cannot run inside a transaction block.
--
-- WHAT IT DOES AND DOES NOT DO. It does not stop the race — two writers still read the same
-- highest number. It makes the loser FAIL instead of silently succeeding, which is what
-- `insertWithOrderNumber` needs in order to retry. Index without allocator is loud but lossy;
-- allocator without index is quiet and still colliding. Both, and the collision is handled.

CREATE UNIQUE INDEX IF NOT EXISTS orders_firebase_restaurant_id_order_number_key
  ON public.orders (firebase_restaurant_id, order_number)
  WHERE firebase_restaurant_id IS NOT NULL AND order_number IS NOT NULL;
